Repository LDMX-Software/ldmx-sw, pull requests merged in 2018-07, with the labels that each got.

#461 Added Birks correction to the Hcal SD.
  SimApplication/include/SimApplication/HcalSD.h
  SimApplication/src/HcalSD.cxx
Labels: enhancement, important

#471 Should fix compiler warning in ClusterAlgoResult
  Event/include/Event/ClusterAlgoResult.h
Labels: cleanup

#473 Add ability to set the vertex using #vertex
  SimApplication/include/SimApplication/LHEEvent.h
  SimApplication/src/LHEEvent.cxx
  SimApplication/src/LHEPrimaryGenerator.cxx
  SimApplication/src/LHEReader.cxx
Labels: enhancement
