Repository LDMX-Software/ldmx-sw, pull requests merged in 2018-03, with the labels that each got.

#442 Adding a seed for the beam smearing
  SimApplication/src/PrimaryGeneratorAction.cxx
Labels: bug

#446 Update v3 recon configuration.
  Configuration/python/v3_recon_skim.py
Labels: config

#440 Iss313: Add Electronuclear biasing
  Biasing/include/Biasing/ElectroNuclearXsecBiasingOperator.h
  Biasing/include/Biasing/TargetENProcessFilter.h
  Biasing/include/Biasing/TargetENProcessFilterMessenger.h
  Biasing/src/ElectroNuclearXsecBiasingOperator.cxx
  Biasing/src/TargetENProcessFilter.cxx
  Biasing/src/TargetENProcessFilterMessenger.cxx
  SimApplication/include/SimApplication/DetectorConstruction.h
  SimApplication/macros/production/4pt0_gev_electron_target_en_biasing_v3_production.mac
  SimApplication/src/DetectorConstruction.cxx
Labels: enhancement, important
