Repository LDMX-Software/ldmx-sw, pull requests merged in 2020-07, with the labels that each got.

#837 Update env script to deal with locally built containers
  scripts/ldmx-env.sh
Labels: enhancement

#845 Forgot to push one last change to Production Image action
  .github/workflows/generate_production_image.yml
Labels: bug

#844 remove PyROOT from necessary compilation components
  CMakeLists.txt
  EventProc/include/EventProc/NonFidEcalVetoProcessor.h
  EventProc/src/NonFidEcalVetoProcessor.cxx
Labels: cleanup

#842 Make trigger output collection name settable
  EventProc/include/EventProc/TriggerProcessor.h
  EventProc/python/simpleTrigger.py
  EventProc/src/TriggerProcessor.cxx
Labels: enhancement

#852 import dictionary file inside Event module
  Event/python/dictionary.py.in
Labels: enhancement

#859 More updates to the environment scripts
  scripts/ldmx-env.sh
Labels: bug, cleanup, config

#864 Change TS digi default PE per MIP from 10 to 100
  EventProc/python/trigScintDigis.py
Labels: TrigScint, config

#865 found EcalHexReadout bug and added some comments to avoid mistake in future
  DetDescr/include/DetDescr/EcalHexReadout.h
  DetDescr/src/EcalHexReadout.cxx
  Detectors/data/ldmx-det-v12-lyso/constants.gdml
  Detectors/data/ldmx-det-v12/constants.gdml
Labels: bug

#871 Update ldmx-env.sh
  scripts/ldmx-env.sh
Labels: bug
