Repository LDMX-Software/ldmx-sw, pull requests merged in 2020-06, with the labels that each got.

#808 Clearing the track map also deletes the trajectory.
  SimApplication/src/TrackMap.cxx
Labels: bug, memory leak fix

#809 v12 detector with LYSO target.
  Detectors/data/ldmx-det-v12-lyso/constants.gdml
  Detectors/data/ldmx-det-v12-lyso/detector.gdml
  Detectors/data/ldmx-det-v12-lyso/ecal.gdml
  Detectors/data/ldmx-det-v12-lyso/hcal.gdml
  Detectors/data/ldmx-det-v12-lyso/magnet.gdml
  Detectors/data/ldmx-det-v12-lyso/recoil.gdml
  Detectors/data/ldmx-det-v12-lyso/scoring_planes.gdml
  Detectors/data/ldmx-det-v12-lyso/tagger.gdml
  Detectors/data/ldmx-det-v12-lyso/target.gdml
Labels: new detector

#828 dump parameters to meta dictionary
  Framework/python/ldmxcfg.py
Labels: config

#831 some small patches on const correctness
  Event/include/Event/RunHeader.h
  Framework/include/Framework/Event.h
Labels: cleanup
